### ISSUE TITLE
sncicd-publish-app 2.0.0 not detecting the correct application version

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd-publish-app#20]
Hi, 

I have encountered an issue after upgrading sncicd-publish-app action in the pipeline from 1.2.0 to 2.0.0. Please find the changes made to the yaml highlighted below:

Before: 
- name: ServiceNow CI/CD Publish App
        id: publish_app   
        uses: ServiceNow/sncicd-publish-app@**_1.2.0_**
        with:
          versionFormat: detect
        env:
            **_snowUsername_**: ${{ secrets.SN_USERNAME }}
            **_snowPassword_**: ${{ secrets.SN_PASSWORD }}
            **_snowSourceInstance_**: ${{ secrets.SN_TEST_INSTANCE }}
            appSysID: ${{ secrets.SN_APP_SYSID }}

After: 
   - name: ServiceNow CI/CD Publish App
        id: publish_app   
        uses: ServiceNow/sncicd-publish-app@**_2.0.0_**
        with:
          versionFormat: detect
        env:
            **_nowUsername_**: ${{ secrets.SN_USERNAME }}
            **_nowPassword_**: ${{ secrets.SN_PASSWORD }}
            **_nowSourceInstance_**: ${{ secrets.SN_TEST_INSTANCE }}
            appSysID: ${{ secrets.SN_APP_SYSID }}

Pasting a screenshot of the error here. The current version is 11.4.0 and I's trying to publish 11.5.0. However the action detects 11.5.0 as current version. 
![image](https://user-images.githubusercontent.com/62088522/121307152-55768f80-c91d-11eb-9f22-97bc1b9c18f8.png)

Thanks
Ramya

**Comment by chiarnglin** [comment]
@ramyaramdasan can you confirm that the app repo doesn't already have 11.5.0 in it? otherwise i'm assuming that your dev instance has 11.5.0, it's committed to Source Control, and now we're trying to publish 11.5.0 while the app repo has 11.4.0 as latest?

**Comment by ramyaramdasan** [comment]
Hi @chiarnglin,

App Repo has 11.3.0 as latest. I got the error when I tried with 11.4.0 and same error for a second attempt with 11.5.0. 

As of now, DPP dev instance (905) has 11.5.0, it's committed to Source Control, and trying to publish 11.5.0 while the app repo has 11.3.0 as latest. Hope this helps. 

![image](https://user-images.githubusercontent.com/62088522/121466628-5cf96f80-c9d5-11eb-9e20-2d681ac66a7b.png)

**Comment by chiarnglin** [comment]
Thank you @ramyaramdasan, our dev has found the bug, we'll make a fix for it!

**Comment by chiarng** [comment]
@ramyaramdasan Sorry about the troubles, but try v2.0.1 now! 
https://github.com/ServiceNow/sncicd-publish-app/releases/tag/2.0.1

**Comment by chiarng** [comment]
Also there's a new feature "incrementBy" parameter that defaults to 0 and allows you to set any integer value for incrementing, so you're not stuck with either 0 or 1 anymore!

**Comment by ramyaramdasan** [comment]
@chiarnglin , thanks for the quick fix. It works now. There is a minor issue with outputs though, both rollback and new versions are set to same value. 

![image](https://user-images.githubusercontent.com/62088522/121671747-9234b900-cacc-11eb-8af3-fa4d850b55e8.png)

Thanks
Ramya

**Comment by chiarng** [comment]
@ramyaramdasan
Hi Ramya,
Thanks for bringing this up! I'm trying to remember why we have `rollbackVersion` in publish-app Action though. The rollback context is set on the instance being installed onto, and I see that the install-app Action has the output for `rollbackVersion`, which makes sense. What is the use case for `rollbackVersion` in the publish-app Action? 
Thanks for reminding me,
Chiarng

**Comment by ramyaramdasan** [comment]
Hi Chiarng (@chiarnglin),

Yes, we use the rollbackVersion output in install-app action. I was closely watching the logs during first pipeline execution with publish-app 2.0,1, and came across this line. While it didn't impact anything, I thought of bringing it to your notice. 

Thanks
Ramya

**Comment by chiarng** [comment]
Thanks Ramya, 
Hmm. If anything, this sounds like a feature that needs to be deprecated, because I can't think of a use case for a `rollbackVersion` in publish-app, especially if it's the wrong version.. In any case for now, I'll table this, we can observe if anyone else has an actual use case for it! 
-Chiarng
