### ISSUE TITLE
Add the versionFormat - detect_without_autoincrement 

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd-publish-app#4]
Hi @chiarnglin ,

It would be great to have the **detect_without_autoincrement** option that we have been using inside Azure Pipelines available on GitHub actions as well. In our model, we would want the team to set the application version manually during a sprint, rather than auto-setting it using a template.

**Comment by chiarnglin** [comment]
https://github.com/ServiceNow/sncicd-publish-app/blob/d0227d08f3bf3184c18fada2a732a02a590a8da4/src/App.ts#L262

https://github.com/ServiceNow/sncicd-publish-app/blob/d0227d08f3bf3184c18fada2a732a02a590a8da4/lib/src/App.js#L249

**Comment by chiarnglin** [comment]
I think the feature we're looking for is to provide a field for how many versions to auto increment in x, y, z, with default set to 0, 0, 0. That way, you can elect to not auto-increment if it doesn't fit your pipeline, or you can choose to sophisticated auto increment behaviors beyond just x.y.z+1

**Comment by ramyaramdasan** [comment]
I think the auto-increment is causing us issue because we are not publishing our app from DEV. We move the application to TEST using GIT Repo and its from TEST that we are publishing it. Which means, the auto-increment would always leave the app version in DEV out of sync. This could particularly cause an issue when a clone is done. Because during clone, whatever version is available on production is what is restored in DEV, while that version would have never existed in DEV. Its actually a matter of serious concern.

**Comment by chiarnglin** [comment]
Lemme see if I get this right

1. Dev: 1.2.3
2. Git repo after Source Control commit: 1.2.3
3. Test: 1.2.3, finish testing
4. Publish from test to App Repo using GitHub Action: 1.2.4
5. Test after publishing: 1.2.4
6. Stage/Prod install from App Repo: 1.2.4
**_7. Back to Dev: 1.2.3 is now out of sync with actual Prod 1.2.4?_**

**Comment by ramyaramdasan** [comment]
Yes! You got it right!

**Comment by ramyaramdasan** [comment]
@chiarnglin,

What I also did today was to clone the instance 905 (DEV in DPP) with 907 (ACC in DPP). I had an application which was in 4.0.1 version on ACC, which was copied over to DEV during clone. Since DEV didn't have 4.0.1, it picked a random version 1.0.7 in DEV.

**Comment by chiarnglin** [comment]
@ramyaramdasan 
Sorry for the delay, the cloning behavior you describe is definitely surprising and unexpected for developer users, and I agree this needed to be addressed. To get this fixed faster (and because I haven't heard of anyone specifically asking for auto-increment), I've simply removed the incrementing logic from the GitHub Action completely. I may need some help verifying the fix actually works as intended. Published as version 1.2.0. 

https://github.com/ServiceNow/sncicd-publish-app/releases/tag/1.2.0 #
